### ISSUE TITLE
Все сессии стали invalid

### ISSUE THREAD

**Issue by Igaresha69** [grede/Steamify#1]
Привет, со вчерашнего вечера все сессии стали не валидными. Грешил бы на сами сессии, но эти же файлы работают в куче других скриптов без проблем. Что-то стимифай поменяли в запросах видимо
![image](https://github.com/user-attachments/assets/eda0b62b-dae0-4d8f-8e60-c0959a68b193)

**Comment by grede** [comment]
проверяю

**Comment by grede** [comment]
исправлено
